// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop___024unit;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(software_interrupt,0,0);
        VL_IN8(external_interrupt,0,0);
        VL_OUT8(uart_tx,0,0);
        CData/*0:0*/ top__DOT__clk;
        CData/*0:0*/ top__DOT__rst;
        CData/*0:0*/ top__DOT__software_interrupt;
        CData/*0:0*/ top__DOT__external_interrupt;
        CData/*0:0*/ top__DOT__uart_tx;
        CData/*0:0*/ top__DOT__cpu_mem_write_en;
        CData/*0:0*/ top__DOT__cpu_mem_read_en;
        CData/*3:0*/ top__DOT__cpu_write_byte_enable;
        CData/*2:0*/ top__DOT__cpu_load_type;
        CData/*0:0*/ top__DOT__timer_valid;
        CData/*0:0*/ top__DOT__timer_interrupt;
        CData/*0:0*/ top__DOT__uart_valid;
        CData/*0:0*/ top__DOT__uart_access;
        CData/*0:0*/ top__DOT__data_mem_access;
        CData/*0:0*/ top__DOT__timer_access;
        CData/*0:0*/ top__DOT__instr_mem_access;
        CData/*0:0*/ top__DOT____Vcellinp__data_mem_inst__rd_en;
        CData/*0:0*/ top__DOT____Vcellinp__data_mem_inst__wr_en;
        CData/*0:0*/ top__DOT____Vcellinp__timer_inst__write_enable;
        CData/*0:0*/ top__DOT____Vcellinp__uart_inst__write_enable;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__clk;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__rst;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__module_mem_wr_en;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__module_mem_rd_en;
        CData/*3:0*/ top__DOT__cpu_inst__DOT__module_write_byte_enable;
        CData/*2:0*/ top__DOT__cpu_inst__DOT__module_load_type;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__timer_interrupt;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__software_interrupt;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__external_interrupt;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__pc_inst0_j_signal;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__stall_pipeline;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__branch_flush;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_rs1_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_rs2_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_rd_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_rs1_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_rs2_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_rd_valid_out;
        CData/*6:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_opcode_out;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_instr_id_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__rf_inst0_rd_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__rf_inst0_wr_en;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_rs1_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_rs2_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_rd_valid_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_rs1_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_rs2_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_rd_addr_out;
        CData/*6:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_opcode_out;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_instr_id_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__execution_flush;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__pipeline_flush;
        CData/*0:0*/ top__DOT__cpu_inst__DOT____Vcellinp__id_ex_inst0__stall;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_inst0_jump_signal_out;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__forward_a;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__forward_b;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_write_enable;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_read_enable;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_valid;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu_inst__DOT__interrupt_pending;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__interrupt_taken;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mret_instruction;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ecall_exception;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ebreak_exception;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_rs1_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_rs2_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_rd_addr_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_jump_signal_out;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_instr_id_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_rd_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0_wr_enable_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0_read_enable_out;
        CData/*3:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0_write_byte_enable_out;
        CData/*2:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0_load_type_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_rs1_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_rs2_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_rd_addr_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_jump_signal_out;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_instr_id_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_rd_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__store_load_hazard;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__wb_inst0_wr_en_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__wb_inst0_rd_addr_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__pc_inst0__DOT__clk;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__pc_inst0__DOT__rst;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__pc_inst0__DOT__j_signal;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__pc_inst0__DOT__stall;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__if_id_inst0__DOT__clk;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__if_id_inst0__DOT__rst;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__if_id_inst0__DOT__stall;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__rs2;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__rs1;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__rd;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__rs1_valid;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__rs2_valid;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__rd_valid;
        CData/*6:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__opcode;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__instr_id;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__is_r_instr;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__is_u_instr;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__is_s_instr;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__is_b_instr;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__is_j_instr;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__is_i_instr;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__is_csr_instr;
        CData/*2:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__func3;
        CData/*6:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__func7;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__rs1_id;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__rs2_id;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__rs1_valid_id;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__rs2_valid_id;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__instr_id_ex;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__rd_ex;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__rd_valid_ex;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__stall_pipeline;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__load_use_detector_inst0__DOT__is_load_in_ex;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__clk;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__rs1;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__rs2;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__rs1_valid;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__rs2_valid;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__rd;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__wr_en;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__clk;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rst;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs1_valid_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs2_valid_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rd_valid_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs1_addr_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs2_addr_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rd_addr_in;
        CData/*6:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__opcode_in;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__instr_id_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__stall;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs1_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs2_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rd_valid_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs1_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs2_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rd_addr_out;
        CData/*6:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__opcode_out;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__instr_id_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__rs1_addr_ex;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__rs2_addr_ex;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__rs1_valid_ex;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__rs2_valid_ex;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__rd_addr_mem;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__rd_valid_mem;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__instr_id_mem;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__rd_addr_wb;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__rd_valid_wb;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__wr_en_wb;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__forward_a;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__forward_b;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__is_mem_load;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__clk;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__rst;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__timer_interrupt;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__software_interrupt;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__external_interrupt;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__interrupt_pending;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__interrupt_taken;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__msie;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__mtie;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__meie;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__mie_global;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__msip;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__mtip;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__meip;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__clk;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__rst;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__write_enable;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__read_enable;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__csr_valid;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__interrupt_pending;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__interrupt_taken;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mret_instruction;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__ecall_exception;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__ebreak_exception;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__timer_interrupt;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__software_interrupt;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__external_interrupt;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs1_addr;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs2_addr;
        CData/*6:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__opcode;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__instr_id;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs1_valid;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs2_valid;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__forward_a;
        CData/*1:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__forward_b;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_valid;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_read_enable;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_write_enable;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__jump_signal;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__flush_pipeline;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__interrupt_pending;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__interrupt_taken;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__mret_instruction;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__ecall_exception;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__ebreak_exception;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_exec_inst__DOT__instr_id;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_exec_inst__DOT__rs1_addr;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_exec_inst__DOT__csr_write_enable;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__alu_inst__DOT__instr_id;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__clk;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rst;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rs1_addr_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rs2_addr_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rd_addr_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__jump_signal_in;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__instr_id_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rd_valid_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rs1_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rs2_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rd_addr_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__jump_signal_out;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__instr_id_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rd_valid_out;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__instr_id;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__wr_enable;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__read_enable;
        CData/*3:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__write_byte_enable;
        CData/*2:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__load_type;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__load_instr_id;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__prev_store_instr_id;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__store_load_hazard;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__is_load;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__is_store;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__addr_match;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__clk;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rst;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rs1_addr_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rs2_addr_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rd_addr_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__jump_signal_in;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__instr_id_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rd_valid_in;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__store_load_hazard;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rs1_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rs2_addr_out;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rd_addr_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__jump_signal_out;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__instr_id_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rd_valid_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__rd_valid_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__rd_addr_in;
        CData/*5:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__instr_id_in;
        CData/*4:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__rd_addr_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__wr_en_out;
        CData/*0:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__is_load_instr;
        CData/*2:0*/ top__DOT__instr_mem_inst__DOT__load_type;
    };
    struct {
        CData/*1:0*/ top__DOT__instr_mem_inst__DOT__unnamedblk1__DOT__byte_offset;
        CData/*7:0*/ top__DOT__instr_mem_inst__DOT__unnamedblk1__DOT__byte_data;
        CData/*0:0*/ top__DOT__data_mem_inst__DOT__clk;
        CData/*0:0*/ top__DOT__data_mem_inst__DOT__wr_en;
        CData/*0:0*/ top__DOT__data_mem_inst__DOT__rd_en;
        CData/*3:0*/ top__DOT__data_mem_inst__DOT__write_byte_enable;
        CData/*2:0*/ top__DOT__data_mem_inst__DOT__load_type;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__byte_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__0__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__1__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__2__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__3__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__4__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__5__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__6__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__7__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__8__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__9__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__10__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__11__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__12__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__13__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__14__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__15__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__16__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__17__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__18__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__19__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__20__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__21__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__22__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__23__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__24__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__25__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__26__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__27__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__28__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__29__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__30__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__31__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__32__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__33__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__34__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__35__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__36__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__37__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__38__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__39__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__40__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__41__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__42__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__43__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__44__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__45__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__46__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__47__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__48__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__49__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__50__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__51__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__52__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__53__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__54__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__55__KET____DOT__reg_data;
    };
    struct {
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__56__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__57__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__58__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__59__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__60__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__61__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__62__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__63__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__64__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__65__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__66__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__67__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__68__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__69__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__70__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__71__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__72__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__73__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__74__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__75__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__76__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__77__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__78__KET____DOT__reg_data;
        CData/*7:0*/ top__DOT__data_mem_inst__DOT__dump_regs__BRA__79__KET____DOT__reg_data;
        CData/*0:0*/ top__DOT__timer_inst__DOT__clk;
        CData/*0:0*/ top__DOT__timer_inst__DOT__rst;
        CData/*0:0*/ top__DOT__timer_inst__DOT__write_enable;
        CData/*0:0*/ top__DOT__timer_inst__DOT__read_enable;
        CData/*0:0*/ top__DOT__timer_inst__DOT__timer_valid;
        CData/*0:0*/ top__DOT__timer_inst__DOT__timer_interrupt;
        CData/*0:0*/ top__DOT__uart_inst__DOT__clk;
        CData/*0:0*/ top__DOT__uart_inst__DOT__rst;
        CData/*0:0*/ top__DOT__uart_inst__DOT__write_enable;
        CData/*0:0*/ top__DOT__uart_inst__DOT__read_enable;
        CData/*0:0*/ top__DOT__uart_inst__DOT__uart_valid;
        CData/*0:0*/ top__DOT__uart_inst__DOT__tx;
        CData/*7:0*/ top__DOT__uart_inst__DOT__tx_data;
        CData/*0:0*/ top__DOT__uart_inst__DOT__tx_busy;
        CData/*0:0*/ top__DOT__uart_inst__DOT__tx_enable;
        CData/*0:0*/ top__DOT__uart_inst__DOT__tx_start_pending;
        CData/*0:0*/ top__DOT__uart_inst__DOT__baud_reload;
        CData/*0:0*/ top__DOT__uart_inst__DOT__tx_fifo_full;
        CData/*0:0*/ top__DOT__uart_inst__DOT__tx_fifo_empty;
        CData/*3:0*/ top__DOT__uart_inst__DOT__tx_state;
        CData/*3:0*/ top__DOT__uart_inst__DOT__tx_bit_count;
        CData/*0:0*/ top__DOT__uart_inst__DOT__tx_out;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst__0;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_addr;
        SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__csr_addr;
        SData/*11:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_addr;
        SData/*15:0*/ top__DOT__instr_mem_inst__DOT__unnamedblk1__DOT__halfword_data;
        SData/*15:0*/ top__DOT__data_mem_inst__DOT__halfword_data;
        SData/*15:0*/ top__DOT__uart_inst__DOT__baud_div;
        SData/*15:0*/ top__DOT__uart_inst__DOT__baud_counter;
        VL_OUT(pc_debug,31,0);
        VL_OUT(instr_debug,31,0);
        IData/*31:0*/ top__DOT__pc_debug;
        IData/*31:0*/ top__DOT__instr_debug;
        IData/*31:0*/ top__DOT__cpu_pc_out;
        IData/*31:0*/ top__DOT__instr_to_cpu;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu_mem_read_addr;
        IData/*31:0*/ top__DOT__cpu_mem_write_addr;
        IData/*31:0*/ top__DOT__cpu_mem_write_data;
        IData/*31:0*/ top__DOT__mem_read_data;
        IData/*31:0*/ top__DOT__data_mem_addr;
        IData/*31:0*/ top__DOT__instr_read_data;
        IData/*31:0*/ top__DOT__timer_read_data;
        IData/*31:0*/ top__DOT__uart_read_data;
        IData/*31:0*/ top__DOT__data_mem_read_data;
        VlWide<32>/*1023:0*/ top__DOT__dumpfile_path;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__module_instr_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__module_read_data_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__module_pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__module_wr_data_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__module_read_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__module_write_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__pc_inst0_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__pc_inst0_jump;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__if_id_pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__if_id_instr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT____Vcellinp__if_id_inst0__instruction_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__decoder_inst0_imm_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__rf_inst0_rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__rf_inst0_rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__rf_inst0_rd_value_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_imm_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0_rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_inst0_exec_output_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_inst0_jump_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_inst0_mem_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_inst0_rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_inst0_rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_read_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_write_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__interrupt_cause;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__interrupt_pc;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_mem_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_exec_output_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0_jump_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0_wr_data_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0_read_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0_wr_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_mem_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_exec_output_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_jump_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0_mem_data_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__forwarded_store_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__wb_inst0_rd_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__pc_inst0__DOT__jump;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__pc_inst0__DOT__out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__pc_inst0__DOT__next_pc;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__if_id_inst0__DOT__pc_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__if_id_inst0__DOT__instruction_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__if_id_inst0__DOT__pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__if_id_inst0__DOT__instruction_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__instr;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu_inst__DOT__decoder_inst0__DOT__imm;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__rd_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__rs1_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__rf_inst0__DOT__rs2_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__imm_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__pc_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs1_value_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs2_value_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__imm_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__id_ex_inst0__DOT__rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__mstatus;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__mie;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__mip;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__interrupt_cause;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__interrupt_pc;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__write_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__read_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__interrupt_cause_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__interrupt_pc_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mstatus;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__misa;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mie;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mtvec;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mscratch;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mepc;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mcause;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mtval;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__mip;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs1;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs2;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__imm;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__pc_input;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__ex_mem_result;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__mem_wb_result;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_read_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_write_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__exec_output;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__jump_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__mem_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__interrupt_cause;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__mtvec;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__mepc;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs1_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__rs2_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_rd_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_exec_inst__DOT__rs1_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_exec_inst__DOT__csr_read_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_exec_inst__DOT__csr_write_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_exec_inst__DOT__rd_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__csr_exec_inst__DOT__uimm;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__alu_inst__DOT__rs1;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__alu_inst__DOT__rs2;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__alu_inst__DOT__imm;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__alu_inst__DOT__pc_input;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__alu_inst__DOT__ALUoutput;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rs1_value_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rs2_value_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__pc_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__mem_addr_in;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__exec_output_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__jump_addr_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__mem_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__exec_output_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__ex_mem_inst0__DOT__jump_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__rs2_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__mem_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__wr_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__read_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_unit_inst0__DOT__wr_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__load_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__prev_store_addr;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__rs2_value;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__store_load_detector_inst0__DOT__forwarded_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rs1_value_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rs2_value_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__pc_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__mem_addr_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__exec_output_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__jump_addr_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__mem_data_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__store_data;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rs1_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__rs2_value_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__pc_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__mem_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__exec_output_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__jump_addr_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__mem_wb_inst0__DOT__mem_data_out;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__rd_value_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__mem_data_in;
        IData/*31:0*/ top__DOT__cpu_inst__DOT__wb_inst0__DOT__rd_value_out;
        IData/*31:0*/ top__DOT__instr_mem_inst__DOT__instr_addr;
        IData/*31:0*/ top__DOT__instr_mem_inst__DOT__instr_addr_p2;
        IData/*31:0*/ top__DOT__instr_mem_inst__DOT__instr;
        IData/*31:0*/ top__DOT__instr_mem_inst__DOT__instr_p2;
        IData/*29:0*/ top__DOT__instr_mem_inst__DOT__unnamedblk1__DOT__word_addr;
        IData/*31:0*/ top__DOT__instr_mem_inst__DOT__unnamedblk1__DOT__word_data;
        IData/*31:0*/ top__DOT__instr_mem_inst__DOT__unnamedblk1__DOT__unnamedblk2__DOT__next_word_data;
        IData/*31:0*/ top__DOT__instr_mem_inst__DOT__unnamedblk1__DOT__unnamedblk3__DOT__next_word_data;
        IData/*31:0*/ top__DOT__data_mem_inst__DOT__addr;
        IData/*31:0*/ top__DOT__data_mem_inst__DOT__wr_data;
        IData/*31:0*/ top__DOT__data_mem_inst__DOT__rd_data_out;
        IData/*31:0*/ top__DOT__data_mem_inst__DOT__word_data;
        IData/*31:0*/ top__DOT__data_mem_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ top__DOT__timer_inst__DOT__addr;
        IData/*31:0*/ top__DOT__timer_inst__DOT__write_data;
        IData/*31:0*/ top__DOT__timer_inst__DOT__read_data;
        IData/*31:0*/ top__DOT__uart_inst__DOT__addr;
        IData/*31:0*/ top__DOT__uart_inst__DOT__write_data;
        IData/*31:0*/ top__DOT__uart_inst__DOT__read_data;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__cycle_counter;
        QData/*63:0*/ top__DOT__timer_inst__DOT__mtime;
        QData/*63:0*/ top__DOT__timer_inst__DOT__mtimecmp;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu_inst__DOT__rf_inst0__DOT__register_file;
        VlUnpacked<IData/*31:0*/, 131072> top__DOT__instr_mem_inst__DOT__instr_ram;
        VlUnpacked<CData/*7:0*/, 1048576> top__DOT__data_mem_inst__DOT__data_ram;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*1:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__NO_FORWARDING = 0U;
    static constexpr CData/*1:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__FORWARD_FROM_MEM = 1U;
    static constexpr CData/*1:0*/ top__DOT__cpu_inst__DOT__forwarding_unit_inst0__DOT__FORWARD_FROM_WB = 2U;
    static constexpr CData/*1:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__NO_FORWARDING = 0U;
    static constexpr CData/*1:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__FORWARD_FROM_MEM = 1U;
    static constexpr CData/*1:0*/ top__DOT__cpu_inst__DOT__ex_unit_inst0__DOT__FORWARD_FROM_WB = 2U;
    static constexpr CData/*3:0*/ top__DOT__uart_inst__DOT__TX_IDLE = 0U;
    static constexpr CData/*3:0*/ top__DOT__uart_inst__DOT__TX_START = 1U;
    static constexpr CData/*3:0*/ top__DOT__uart_inst__DOT__TX_DATA = 2U;
    static constexpr CData/*3:0*/ top__DOT__uart_inst__DOT__TX_STOP = 3U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MSTATUS = 0x0300U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MISA = 0x0301U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MIE = 0x0304U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MTVEC = 0x0305U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MSCRATCH = 0x0340U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MEPC = 0x0341U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MCAUSE = 0x0342U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MTVAL = 0x0343U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_MIP = 0x0344U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_CYCLE = 0x0c00U;
    static constexpr SData/*11:0*/ top__DOT__cpu_inst__DOT__csr_file_inst__DOT__CSR_CYCLEH = 0x0c80U;
    static constexpr SData/*15:0*/ top__DOT__uart_inst__DOT__DEFAULT_BAUD_DIVISOR = 0x01b2U;
    static constexpr IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__MACHINE_SOFTWARE_INTERRUPT = 0x80000003U;
    static constexpr IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__MACHINE_TIMER_INTERRUPT = 0x80000007U;
    static constexpr IData/*31:0*/ top__DOT__cpu_inst__DOT__int_ctrl_inst__DOT__MACHINE_EXTERNAL_INTERRUPT = 0x8000000bU;
    static constexpr IData/*31:0*/ top__DOT__instr_mem_inst__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__instr_mem_inst__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__instr_mem_inst__DOT__MEM_SIZE = 0x00020000U;
    static constexpr IData/*31:0*/ top__DOT__data_mem_inst__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__data_mem_inst__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__data_mem_inst__DOT__MEM_SIZE = 0x00100000U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
